### ISSUE TITLE
Add new widgets

### ISSUE THREAD

**Issue by infiniteoverflow** [infiniteoverflow/Flutter-Examples#1]
Contribute any widgets you feel interesting. Do provide documentation on its usage as given in the existing widget folders.

**Comment by marcos1martins** [comment]
Hello, I can work on it. Which widgets are left?

**Comment by infiniteoverflow** [comment]
There are tons of great widgets still left to be contributed. For eg : Various Bottom navigation bars , Various Floating Action buttons ,etc

**Comment by marcos1martins** [comment]
So, I didn't understand. BottomNavigationBar and FloatingActionButton already have code samples in this repository. Do you want to improve what you already have?

**Comment by infiniteoverflow** [comment]
No , i mean there are plenty of variants in BottomNavigationBar and FABs , i have just added the basic material design one. 

https://pub.dev/packages?q=bottom+bar
https://pub.dev/packages?q=Floating+Action+Buttons

These are some suggestions, you can contribute ANY widget , which you feel could be helpful for a beginner to use.

**Comment by arjitmishra** [comment]
So you want us to have a better UI design for the widgets?

**Comment by marcos1martins** [comment]
I am sending an implementation of a Form with validators.
A demonstration of how to use the Form and TextFormField classes and validate fields such as name, email and phone.

**Comment by marcos1martins** [comment]
> No , i mean there are plenty of variants in BottomNavigationBar and FABs , i have just added the basic material design one.
> 
> https://pub.dev/packages?q=bottom+bar
> https://pub.dev/packages?q=Floating+Action+Buttons
> 
> These are some suggestions, you can contribute ANY widget , which you feel could be helpful for a beginner to use.

Ok I'll do it.
BottomNavigationBar for me.

**Comment by infiniteoverflow** [comment]
> So you want us to have a better UI design for the widgets?

I want everyone to add widgets which they like. It could be anything.
